export const countriesAlpha_2_codelist = [
  {
    country: "Afghanistan",
    alpha_2_code: "AF",
    alpha_3_code: "AFG",
    numeric: "004",
  },
  {
    country: "Albania",
    alpha_2_code: "AL",
    alpha_3_code: "ALB",
    numeric: "008",
  },
  {
    country: "Algeria",
    alpha_2_code: "DZ",
    alpha_3_code: "DZA",
    numeric: "012",
  },
  {
    country: "American Samoa",
    alpha_2_code: "AS",
    alpha_3_code: "ASM",
    numeric: "016",
  },
  {
    country: "Andorra",
    alpha_2_code: "AD",
    alpha_3_code: "AND",
    numeric: "020",
  },
  {
    country: "Angola",
    alpha_2_code: "AO",
    alpha_3_code: "AGO",
    numeric: "024",
  },
  {
    country: "Anguilla",
    alpha_2_code: "AI",
    alpha_3_code: "AIA",
    numeric: "660",
  },
  {
    country: "Antarctica",
    alpha_2_code: "AQ",
    alpha_3_code: "ATA",
    numeric: "010",
  },
  {
    country: "Antigua and Barbuda",
    alpha_2_code: "AG",
    alpha_3_code: "ATG",
    numeric: "028",
  },
  {
    country: "Argentina",
    alpha_2_code: "AR",
    alpha_3_code: "ARG",
    numeric: "032",
  },
  {
    country: "Armenia",
    alpha_2_code: "AM",
    alpha_3_code: "ARM",
    numeric: "051",
  },
  {
    country: "Aruba",
    alpha_2_code: "AW",
    alpha_3_code: "ABW",
    numeric: "533",
  },
  {
    country: "Australia",
    alpha_2_code: "AU",
    alpha_3_code: "AUS",
    numeric: "036",
  },
  {
    country: "Austria",
    alpha_2_code: "AT",
    alpha_3_code: "AUT",
    numeric: "040",
  },
  {
    country: "Azerbaijan",
    alpha_2_code: "AZ",
    alpha_3_code: "AZE",
    numeric: "031",
  },
  {
    country: "Bahamas (the)",
    alpha_2_code: "BS",
    alpha_3_code: "BHS",
    numeric: "044",
  },
  {
    country: "Bahrain",
    alpha_2_code: "BH",
    alpha_3_code: "BHR",
    numeric: "048",
  },
  {
    country: "Bangladesh",
    alpha_2_code: "BD",
    alpha_3_code: "BGD",
    numeric: "050",
  },
  {
    country: "Barbados",
    alpha_2_code: "BB",
    alpha_3_code: "BRB",
    numeric: "052",
  },
  {
    country: "Belarus",
    alpha_2_code: "BY",
    alpha_3_code: "BLR",
    numeric: "112",
  },
  {
    country: "Belgium",
    alpha_2_code: "BE",
    alpha_3_code: "BEL",
    numeric: "056",
  },
  {
    country: "Belize",
    alpha_2_code: "BZ",
    alpha_3_code: "BLZ",
    numeric: "084",
  },
  {
    country: "Benin",
    alpha_2_code: "BJ",
    alpha_3_code: "BEN",
    numeric: "204",
  },
  {
    country: "Bermuda",
    alpha_2_code: "BM",
    alpha_3_code: "BMU",
    numeric: "060",
  },
  {
    country: "Bhutan",
    alpha_2_code: "BT",
    alpha_3_code: "BTN",
    numeric: "064",
  },
  {
    country: "Bolivia (Plurinational State of)",
    alpha_2_code: "BO",
    alpha_3_code: "BOL",
    numeric: "068",
  },
  {
    country: "Bonaire, Sint Eustatius and Saba",
    alpha_2_code: "BQ",
    alpha_3_code: "BES",
    numeric: "535",
  },
  {
    country: "Bosnia and Herzegovina",
    alpha_2_code: "BA",
    alpha_3_code: "BIH",
    numeric: "070",
  },
  {
    country: "Botswana",
    alpha_2_code: "BW",
    alpha_3_code: "BWA",
    numeric: "072",
  },
  {
    country: "Bouvet Island",
    alpha_2_code: "BV",
    alpha_3_code: "BVT",
    numeric: "074",
  },
  {
    country: "Brazil",
    alpha_2_code: "BR",
    alpha_3_code: "BRA",
    numeric: "076",
  },
  {
    country: "British Indian Ocean Territory (the)",
    alpha_2_code: "IO",
    alpha_3_code: "IOT",
    numeric: "086",
  },
  {
    country: "Brunei Darussalam",
    alpha_2_code: "BN",
    alpha_3_code: "BRN",
    numeric: "096",
  },
  {
    country: "Bulgaria",
    alpha_2_code: "BG",
    alpha_3_code: "BGR",
    numeric: "100",
  },
  {
    country: "Burkina Faso",
    alpha_2_code: "BF",
    alpha_3_code: "BFA",
    numeric: "854",
  },
  {
    country: "Burundi",
    alpha_2_code: "BI",
    alpha_3_code: "BDI",
    numeric: "108",
  },
  {
    country: "Cabo Verde",
    alpha_2_code: "CV",
    alpha_3_code: "CPV",
    numeric: "132",
  },
  {
    country: "Cambodia",
    alpha_2_code: "KH",
    alpha_3_code: "KHM",
    numeric: "116",
  },
  {
    country: "Cameroon",
    alpha_2_code: "CM",
    alpha_3_code: "CMR",
    numeric: "120",
  },
  {
    country: "Canada",
    alpha_2_code: "CA",
    alpha_3_code: "CAN",
    numeric: "124",
  },
  {
    country: "Cayman Islands (the)",
    alpha_2_code: "KY",
    alpha_3_code: "CYM",
    numeric: "136",
  },
  {
    country: "Central African Republic (the)",
    alpha_2_code: "CF",
    alpha_3_code: "CAF",
    numeric: "140",
  },
  {
    country: "Chad",
    alpha_2_code: "TD",
    alpha_3_code: "TCD",
    numeric: "148",
  },
  {
    country: "Chile",
    alpha_2_code: "CL",
    alpha_3_code: "CHL",
    numeric: "152",
  },
  {
    country: "China",
    alpha_2_code: "CN",
    alpha_3_code: "CHN",
    numeric: "156",
  },
  {
    country: "Christmas Island",
    alpha_2_code: "CX",
    alpha_3_code: "CXR",
    numeric: "162",
  },
  {
    country: "Cocos (Keeling) Islands (the)",
    alpha_2_code: "CC",
    alpha_3_code: "CCK",
    numeric: "166",
  },
  {
    country: "Colombia",
    alpha_2_code: "CO",
    alpha_3_code: "COL",
    numeric: "170",
  },
  {
    country: "Comoros (the)",
    alpha_2_code: "KM",
    alpha_3_code: "COM",
    numeric: "174",
  },
  {
    country: "Congo (the Democratic Republic of the)",
    alpha_2_code: "CD",
    alpha_3_code: "COD",
    numeric: "180",
  },
  {
    country: "Congo (the)",
    alpha_2_code: "CG",
    alpha_3_code: "COG",
    numeric: "178",
  },
  {
    country: "Cook Islands (the)",
    alpha_2_code: "CK",
    alpha_3_code: "COK",
    numeric: "184",
  },
  {
    country: "Costa Rica",
    alpha_2_code: "CR",
    alpha_3_code: "CRI",
    numeric: "188",
  },
  {
    country: "Croatia",
    alpha_2_code: "HR",
    alpha_3_code: "HRV",
    numeric: "191",
  },
  {
    country: "Cuba",
    alpha_2_code: "CU",
    alpha_3_code: "CUB",
    numeric: "192",
  },
  {
    country: "Curaçao",
    alpha_2_code: "CW",
    alpha_3_code: "CUW",
    numeric: "531",
  },
  {
    country: "Cyprus",
    alpha_2_code: "CY",
    alpha_3_code: "CYP",
    numeric: "196",
  },
  {
    country: "Czechia",
    alpha_2_code: "CZ",
    alpha_3_code: "CZE",
    numeric: "203",
  },
  {
    country: "Côte d'Ivoire",
    alpha_2_code: "CI",
    alpha_3_code: "CIV",
    numeric: "384",
  },
  {
    country: "Denmark",
    alpha_2_code: "DK",
    alpha_3_code: "DNK",
    numeric: "208",
  },
  {
    country: "Djibouti",
    alpha_2_code: "DJ",
    alpha_3_code: "DJI",
    numeric: "262",
  },
  {
    country: "Dominica",
    alpha_2_code: "DM",
    alpha_3_code: "DMA",
    numeric: "212",
  },
  {
    country: "Dominican Republic (the)",
    alpha_2_code: "DO",
    alpha_3_code: "DOM",
    numeric: "214",
  },
  {
    country: "Ecuador",
    alpha_2_code: "EC",
    alpha_3_code: "ECU",
    numeric: "218",
  },
  {
    country: "Egypt",
    alpha_2_code: "EG",
    alpha_3_code: "EGY",
    numeric: "818",
  },
  {
    country: "El Salvador",
    alpha_2_code: "SV",
    alpha_3_code: "SLV",
    numeric: "222",
  },
  {
    country: "Equatorial Guinea",
    alpha_2_code: "GQ",
    alpha_3_code: "GNQ",
    numeric: "226",
  },
  {
    country: "Eritrea",
    alpha_2_code: "ER",
    alpha_3_code: "ERI",
    numeric: "232",
  },
  {
    country: "Estonia",
    alpha_2_code: "EE",
    alpha_3_code: "EST",
    numeric: "233",
  },
  {
    country: "Eswatini",
    alpha_2_code: "SZ",
    alpha_3_code: "SWZ",
    numeric: "748",
  },
  {
    country: "Ethiopia",
    alpha_2_code: "ET",
    alpha_3_code: "ETH",
    numeric: "231",
  },
  {
    country: "Falkland Islands (the) [Malvinas]",
    alpha_2_code: "FK",
    alpha_3_code: "FLK",
    numeric: "238",
  },
  {
    country: "Faroe Islands (the)",
    alpha_2_code: "FO",
    alpha_3_code: "FRO",
    numeric: "234",
  },
  {
    country: "Fiji",
    alpha_2_code: "FJ",
    alpha_3_code: "FJI",
    numeric: "242",
  },
  {
    country: "Finland",
    alpha_2_code: "FI",
    alpha_3_code: "FIN",
    numeric: "246",
  },
  {
    country: "France",
    alpha_2_code: "FR",
    alpha_3_code: "FRA",
    numeric: "250",
  },
  {
    country: "French Guiana",
    alpha_2_code: "GF",
    alpha_3_code: "GUF",
    numeric: "254",
  },
  {
    country: "French Polynesia",
    alpha_2_code: "PF",
    alpha_3_code: "PYF",
    numeric: "258",
  },
  {
    country: "French Southern Territories (the)",
    alpha_2_code: "TF",
    alpha_3_code: "ATF",
    numeric: "260",
  },
  {
    country: "Gabon",
    alpha_2_code: "GA",
    alpha_3_code: "GAB",
    numeric: "266",
  },
  {
    country: "Gambia (the)",
    alpha_2_code: "GM",
    alpha_3_code: "GMB",
    numeric: "270",
  },
  {
    country: "Georgia",
    alpha_2_code: "GE",
    alpha_3_code: "GEO",
    numeric: "268",
  },
  {
    country: "Germany",
    alpha_2_code: "DE",
    alpha_3_code: "DEU",
    numeric: "276",
  },
  {
    country: "Ghana",
    alpha_2_code: "GH",
    alpha_3_code: "GHA",
    numeric: "288",
  },
  {
    country: "Gibraltar",
    alpha_2_code: "GI",
    alpha_3_code: "GIB",
    numeric: "292",
  },
  {
    country: "Greece",
    alpha_2_code: "GR",
    alpha_3_code: "GRC",
    numeric: "300",
  },
  {
    country: "Greenland",
    alpha_2_code: "GL",
    alpha_3_code: "GRL",
    numeric: "304",
  },
  {
    country: "Grenada",
    alpha_2_code: "GD",
    alpha_3_code: "GRD",
    numeric: "308",
  },
  {
    country: "Guadeloupe",
    alpha_2_code: "GP",
    alpha_3_code: "GLP",
    numeric: "312",
  },
  {
    country: "Guam",
    alpha_2_code: "GU",
    alpha_3_code: "GUM",
    numeric: "316",
  },
  {
    country: "Guatemala",
    alpha_2_code: "GT",
    alpha_3_code: "GTM",
    numeric: "320",
  },
  {
    country: "Guernsey",
    alpha_2_code: "GG",
    alpha_3_code: "GGY",
    numeric: "831",
  },
  {
    country: "Guinea",
    alpha_2_code: "GN",
    alpha_3_code: "GIN",
    numeric: "324",
  },
  {
    country: "Guinea-Bissau",
    alpha_2_code: "GW",
    alpha_3_code: "GNB",
    numeric: "624",
  },
  {
    country: "Guyana",
    alpha_2_code: "GY",
    alpha_3_code: "GUY",
    numeric: "328",
  },
  {
    country: "Haiti",
    alpha_2_code: "HT",
    alpha_3_code: "HTI",
    numeric: "332",
  },
  {
    country: "Heard Island and McDonald Islands",
    alpha_2_code: "HM",
    alpha_3_code: "HMD",
    numeric: "334",
  },
  {
    country: "Holy See (the)",
    alpha_2_code: "VA",
    alpha_3_code: "VAT",
    numeric: "336",
  },
  {
    country: "Honduras",
    alpha_2_code: "HN",
    alpha_3_code: "HND",
    numeric: "340",
  },
  {
    country: "Hong Kong",
    alpha_2_code: "HK",
    alpha_3_code: "HKG",
    numeric: "344",
  },
  {
    country: "Hungary",
    alpha_2_code: "HU",
    alpha_3_code: "HUN",
    numeric: "348",
  },
  {
    country: "Iceland",
    alpha_2_code: "IS",
    alpha_3_code: "ISL",
    numeric: "352",
  },
  {
    country: "India",
    alpha_2_code: "IN",
    alpha_3_code: "IND",
    numeric: "356",
  },
  {
    country: "Indonesia",
    alpha_2_code: "ID",
    alpha_3_code: "IDN",
    numeric: "360",
  },
  {
    country: "Iran (Islamic Republic of)",
    alpha_2_code: "IR",
    alpha_3_code: "IRN",
    numeric: "364",
  },
  {
    country: "Iraq",
    alpha_2_code: "IQ",
    alpha_3_code: "IRQ",
    numeric: "368",
  },
  {
    country: "Ireland",
    alpha_2_code: "IE",
    alpha_3_code: "IRL",
    numeric: "372",
  },
  {
    country: "Isle of Man",
    alpha_2_code: "IM",
    alpha_3_code: "IMN",
    numeric: "833",
  },
  {
    country: "Israel",
    alpha_2_code: "IL",
    alpha_3_code: "ISR",
    numeric: "376",
  },
  {
    country: "Italy",
    alpha_2_code: "IT",
    alpha_3_code: "ITA",
    numeric: "380",
  },
  {
    country: "Jamaica",
    alpha_2_code: "JM",
    alpha_3_code: "JAM",
    numeric: "388",
  },
  {
    country: "Japan",
    alpha_2_code: "JP",
    alpha_3_code: "JPN",
    numeric: "392",
  },
  {
    country: "Jersey",
    alpha_2_code: "JE",
    alpha_3_code: "JEY",
    numeric: "832",
  },
  {
    country: "Jordan",
    alpha_2_code: "JO",
    alpha_3_code: "JOR",
    numeric: "400",
  },
  {
    country: "Kazakhstan",
    alpha_2_code: "KZ",
    alpha_3_code: "KAZ",
    numeric: "398",
  },
  {
    country: "Kenya",
    alpha_2_code: "KE",
    alpha_3_code: "KEN",
    numeric: "404",
  },
  {
    country: "Kiribati",
    alpha_2_code: "KI",
    alpha_3_code: "KIR",
    numeric: "296",
  },
  {
    country: "Korea (the Democratic People's Republic of)",
    alpha_2_code: "KP",
    alpha_3_code: "PRK",
    numeric: "408",
  },
  {
    country: "Korea (the Republic of)",
    alpha_2_code: "KR",
    alpha_3_code: "KOR",
    numeric: "410",
  },
  {
    country: "Kuwait",
    alpha_2_code: "KW",
    alpha_3_code: "KWT",
    numeric: "414",
  },
  {
    country: "Kyrgyzstan",
    alpha_2_code: "KG",
    alpha_3_code: "KGZ",
    numeric: "417",
  },
  {
    country: "Lao People's Democratic Republic (the)",
    alpha_2_code: "LA",
    alpha_3_code: "LAO",
    numeric: "418",
  },
  {
    country: "Latvia",
    alpha_2_code: "LV",
    alpha_3_code: "LVA",
    numeric: "428",
  },
  {
    country: "Lebanon",
    alpha_2_code: "LB",
    alpha_3_code: "LBN",
    numeric: "422",
  },
  {
    country: "Lesotho",
    alpha_2_code: "LS",
    alpha_3_code: "LSO",
    numeric: "426",
  },
  {
    country: "Liberia",
    alpha_2_code: "LR",
    alpha_3_code: "LBR",
    numeric: "430",
  },
  {
    country: "Libya",
    alpha_2_code: "LY",
    alpha_3_code: "LBY",
    numeric: "434",
  },
  {
    country: "Liechtenstein",
    alpha_2_code: "LI",
    alpha_3_code: "LIE",
    numeric: "438",
  },
  {
    country: "Lithuania",
    alpha_2_code: "LT",
    alpha_3_code: "LTU",
    numeric: "440",
  },
  {
    country: "Luxembourg",
    alpha_2_code: "LU",
    alpha_3_code: "LUX",
    numeric: "442",
  },
  {
    country: "Macao",
    alpha_2_code: "MO",
    alpha_3_code: "MAC",
    numeric: "446",
  },
  {
    country: "Madagascar",
    alpha_2_code: "MG",
    alpha_3_code: "MDG",
    numeric: "450",
  },
  {
    country: "Malawi",
    alpha_2_code: "MW",
    alpha_3_code: "MWI",
    numeric: "454",
  },
  {
    country: "Malaysia",
    alpha_2_code: "MY",
    alpha_3_code: "MYS",
    numeric: "458",
  },
  {
    country: "Maldives",
    alpha_2_code: "MV",
    alpha_3_code: "MDV",
    numeric: "462",
  },
  {
    country: "Mali",
    alpha_2_code: "ML",
    alpha_3_code: "MLI",
    numeric: "466",
  },
  {
    country: "Malta",
    alpha_2_code: "MT",
    alpha_3_code: "MLT",
    numeric: "470",
  },
  {
    country: "Marshall Islands (the)",
    alpha_2_code: "MH",
    alpha_3_code: "MHL",
    numeric: "584",
  },
  {
    country: "Martinique",
    alpha_2_code: "MQ",
    alpha_3_code: "MTQ",
    numeric: "474",
  },
  {
    country: "Mauritania",
    alpha_2_code: "MR",
    alpha_3_code: "MRT",
    numeric: "478",
  },
  {
    country: "Mauritius",
    alpha_2_code: "MU",
    alpha_3_code: "MUS",
    numeric: "480",
  },
  {
    country: "Mayotte",
    alpha_2_code: "YT",
    alpha_3_code: "MYT",
    numeric: "175",
  },
  {
    country: "Mexico",
    alpha_2_code: "MX",
    alpha_3_code: "MEX",
    numeric: "484",
  },
  {
    country: "Micronesia (Federated States of)",
    alpha_2_code: "FM",
    alpha_3_code: "FSM",
    numeric: "583",
  },
  {
    country: "Moldova (the Republic of)",
    alpha_2_code: "MD",
    alpha_3_code: "MDA",
    numeric: "498",
  },
  {
    country: "Monaco",
    alpha_2_code: "MC",
    alpha_3_code: "MCO",
    numeric: "492",
  },
  {
    country: "Mongolia",
    alpha_2_code: "MN",
    alpha_3_code: "MNG",
    numeric: "496",
  },
  {
    country: "Montenegro",
    alpha_2_code: "ME",
    alpha_3_code: "MNE",
    numeric: "499",
  },
  {
    country: "Montserrat",
    alpha_2_code: "MS",
    alpha_3_code: "MSR",
    numeric: "500",
  },
  {
    country: "Morocco",
    alpha_2_code: "MA",
    alpha_3_code: "MAR",
    numeric: "504",
  },
  {
    country: "Mozambique",
    alpha_2_code: "MZ",
    alpha_3_code: "MOZ",
    numeric: "508",
  },
  {
    country: "Myanmar",
    alpha_2_code: "MM",
    alpha_3_code: "MMR",
    numeric: "104",
  },
  {
    country: "Namibia",
    alpha_2_code: "NA",
    alpha_3_code: "NAM",
    numeric: "516",
  },
  {
    country: "Nauru",
    alpha_2_code: "NR",
    alpha_3_code: "NRU",
    numeric: "520",
  },
  {
    country: "Nepal",
    alpha_2_code: "NP",
    alpha_3_code: "NPL",
    numeric: "524",
  },
  {
    country: "Netherlands (the)",
    alpha_2_code: "NL",
    alpha_3_code: "NLD",
    numeric: "528",
  },
  {
    country: "New Caledonia",
    alpha_2_code: "NC",
    alpha_3_code: "NCL",
    numeric: "540",
  },
  {
    country: "New Zealand",
    alpha_2_code: "NZ",
    alpha_3_code: "NZL",
    numeric: "554",
  },
  {
    country: "Nicaragua",
    alpha_2_code: "NI",
    alpha_3_code: "NIC",
    numeric: "558",
  },
  {
    country: "Niger (the)",
    alpha_2_code: "NE",
    alpha_3_code: "NER",
    numeric: "562",
  },
  {
    country: "Nigeria",
    alpha_2_code: "NG",
    alpha_3_code: "NGA",
    numeric: "566",
  },
  {
    country: "Niue",
    alpha_2_code: "NU",
    alpha_3_code: "NIU",
    numeric: "570",
  },
  {
    country: "Norfolk Island",
    alpha_2_code: "NF",
    alpha_3_code: "NFK",
    numeric: "574",
  },
  {
    country: "Northern Mariana Islands (the)",
    alpha_2_code: "MP",
    alpha_3_code: "MNP",
    numeric: "580",
  },
  {
    country: "Norway",
    alpha_2_code: "NO",
    alpha_3_code: "NOR",
    numeric: "578",
  },
  {
    country: "Oman",
    alpha_2_code: "OM",
    alpha_3_code: "OMN",
    numeric: "512",
  },
  {
    country: "Pakistan",
    alpha_2_code: "PK",
    alpha_3_code: "PAK",
    numeric: "586",
  },
  {
    country: "Palau",
    alpha_2_code: "PW",
    alpha_3_code: "PLW",
    numeric: "585",
  },
  {
    country: "Palestine, State of",
    alpha_2_code: "PS",
    alpha_3_code: "PSE",
    numeric: "275",
  },
  {
    country: "Panama",
    alpha_2_code: "PA",
    alpha_3_code: "PAN",
    numeric: "591",
  },
  {
    country: "Papua New Guinea",
    alpha_2_code: "PG",
    alpha_3_code: "PNG",
    numeric: "598",
  },
  {
    country: "Paraguay",
    alpha_2_code: "PY",
    alpha_3_code: "PRY",
    numeric: "600",
  },
  {
    country: "Peru",
    alpha_2_code: "PE",
    alpha_3_code: "PER",
    numeric: "604",
  },
  {
    country: "Philippines (the)",
    alpha_2_code: "PH",
    alpha_3_code: "PHL",
    numeric: "608",
  },
  {
    country: "Pitcairn",
    alpha_2_code: "PN",
    alpha_3_code: "PCN",
    numeric: "612",
  },
  {
    country: "Poland",
    alpha_2_code: "PL",
    alpha_3_code: "POL",
    numeric: "616",
  },
  {
    country: "Portugal",
    alpha_2_code: "PT",
    alpha_3_code: "PRT",
    numeric: "620",
  },
  {
    country: "Puerto Rico",
    alpha_2_code: "PR",
    alpha_3_code: "PRI",
    numeric: "630",
  },
  {
    country: "Qatar",
    alpha_2_code: "QA",
    alpha_3_code: "QAT",
    numeric: "634",
  },
  {
    country: "Republic of North Macedonia",
    alpha_2_code: "MK",
    alpha_3_code: "MKD",
    numeric: "807",
  },
  {
    country: "Romania",
    alpha_2_code: "RO",
    alpha_3_code: "ROU",
    numeric: "642",
  },
  {
    country: "Russian Federation (the)",
    alpha_2_code: "RU",
    alpha_3_code: "RUS",
    numeric: "643",
  },
  {
    country: "Rwanda",
    alpha_2_code: "RW",
    alpha_3_code: "RWA",
    numeric: "646",
  },
  {
    country: "Réunion",
    alpha_2_code: "RE",
    alpha_3_code: "REU",
    numeric: "638",
  },
  {
    country: "Saint Barthélemy",
    alpha_2_code: "BL",
    alpha_3_code: "BLM",
    numeric: "652",
  },
  {
    country: "Saint Helena, Ascension and Tristan da Cunha",
    alpha_2_code: "SH",
    alpha_3_code: "SHN",
    numeric: "654",
  },
  {
    country: "Saint Kitts and Nevis",
    alpha_2_code: "KN",
    alpha_3_code: "KNA",
    numeric: "659",
  },
  {
    country: "Saint Lucia",
    alpha_2_code: "LC",
    alpha_3_code: "LCA",
    numeric: "662",
  },
  {
    country: "Saint Martin (French part)",
    alpha_2_code: "MF",
    alpha_3_code: "MAF",
    numeric: "663",
  },
  {
    country: "Saint Pierre and Miquelon",
    alpha_2_code: "PM",
    alpha_3_code: "SPM",
    numeric: "666",
  },
  {
    country: "Saint Vincent and the Grenadines",
    alpha_2_code: "VC",
    alpha_3_code: "VCT",
    numeric: "670",
  },
  {
    country: "Samoa",
    alpha_2_code: "WS",
    alpha_3_code: "WSM",
    numeric: "882",
  },
  {
    country: "San Marino",
    alpha_2_code: "SM",
    alpha_3_code: "SMR",
    numeric: "674",
  },
  {
    country: "Sao Tome and Principe",
    alpha_2_code: "ST",
    alpha_3_code: "STP",
    numeric: "678",
  },
  {
    country: "Saudi Arabia",
    alpha_2_code: "SA",
    alpha_3_code: "SAU",
    numeric: "682",
  },
  {
    country: "Senegal",
    alpha_2_code: "SN",
    alpha_3_code: "SEN",
    numeric: "686",
  },
  {
    country: "Serbia",
    alpha_2_code: "RS",
    alpha_3_code: "SRB",
    numeric: "688",
  },
  {
    country: "Seychelles",
    alpha_2_code: "SC",
    alpha_3_code: "SYC",
    numeric: "690",
  },
  {
    country: "Sierra Leone",
    alpha_2_code: "SL",
    alpha_3_code: "SLE",
    numeric: "694",
  },
  {
    country: "Singapore",
    alpha_2_code: "SG",
    alpha_3_code: "SGP",
    numeric: "702",
  },
  {
    country: "Sint Maarten (Dutch part)",
    alpha_2_code: "SX",
    alpha_3_code: "SXM",
    numeric: "534",
  },
  {
    country: "Slovakia",
    alpha_2_code: "SK",
    alpha_3_code: "SVK",
    numeric: "703",
  },
  {
    country: "Slovenia",
    alpha_2_code: "SI",
    alpha_3_code: "SVN",
    numeric: "705",
  },
  {
    country: "Solomon Islands",
    alpha_2_code: "SB",
    alpha_3_code: "SLB",
    numeric: "090",
  },
  {
    country: "Somalia",
    alpha_2_code: "SO",
    alpha_3_code: "SOM",
    numeric: "706",
  },
  {
    country: "South Africa",
    alpha_2_code: "ZA",
    alpha_3_code: "ZAF",
    numeric: "710",
  },
  {
    country: "South Georgia and the South Sandwich Islands",
    alpha_2_code: "GS",
    alpha_3_code: "SGS",
    numeric: "239",
  },
  {
    country: "South Sudan",
    alpha_2_code: "SS",
    alpha_3_code: "SSD",
    numeric: "728",
  },
  {
    country: "Spain",
    alpha_2_code: "ES",
    alpha_3_code: "ESP",
    numeric: "724",
  },
  {
    country: "Sri Lanka",
    alpha_2_code: "LK",
    alpha_3_code: "LKA",
    numeric: "144",
  },
  {
    country: "Sudan (the)",
    alpha_2_code: "SD",
    alpha_3_code: "SDN",
    numeric: "729",
  },
  {
    country: "Suriname",
    alpha_2_code: "SR",
    alpha_3_code: "SUR",
    numeric: "740",
  },
  {
    country: "Svalbard and Jan Mayen",
    alpha_2_code: "SJ",
    alpha_3_code: "SJM",
    numeric: "744",
  },
  {
    country: "Sweden",
    alpha_2_code: "SE",
    alpha_3_code: "SWE",
    numeric: "752",
  },
  {
    country: "Switzerland",
    alpha_2_code: "CH",
    alpha_3_code: "CHE",
    numeric: "756",
  },
  {
    country: "Syrian Arab Republic",
    alpha_2_code: "SY",
    alpha_3_code: "SYR",
    numeric: "760",
  },
  {
    country: "Taiwan (Province of China)",
    alpha_2_code: "TW",
    alpha_3_code: "TWN",
    numeric: "158",
  },
  {
    country: "Tajikistan",
    alpha_2_code: "TJ",
    alpha_3_code: "TJK",
    numeric: "762",
  },
  {
    country: "Tanzania, United Republic of",
    alpha_2_code: "TZ",
    alpha_3_code: "TZA",
    numeric: "834",
  },
  {
    country: "Thailand",
    alpha_2_code: "TH",
    alpha_3_code: "THA",
    numeric: "764",
  },
  {
    country: "Timor-Leste",
    alpha_2_code: "TL",
    alpha_3_code: "TLS",
    numeric: "626",
  },
  {
    country: "Togo",
    alpha_2_code: "TG",
    alpha_3_code: "TGO",
    numeric: "768",
  },
  {
    country: "Tokelau",
    alpha_2_code: "TK",
    alpha_3_code: "TKL",
    numeric: "772",
  },
  {
    country: "Tonga",
    alpha_2_code: "TO",
    alpha_3_code: "TON",
    numeric: "776",
  },
  {
    country: "Trinidad and Tobago",
    alpha_2_code: "TT",
    alpha_3_code: "TTO",
    numeric: "780",
  },
  {
    country: "Tunisia",
    alpha_2_code: "TN",
    alpha_3_code: "TUN",
    numeric: "788",
  },
  {
    country: "Turkey",
    alpha_2_code: "TR",
    alpha_3_code: "TUR",
    numeric: "792",
  },
  {
    country: "Turkmenistan",
    alpha_2_code: "TM",
    alpha_3_code: "TKM",
    numeric: "795",
  },
  {
    country: "Turks and Caicos Islands (the)",
    alpha_2_code: "TC",
    alpha_3_code: "TCA",
    numeric: "796",
  },
  {
    country: "Tuvalu",
    alpha_2_code: "TV",
    alpha_3_code: "TUV",
    numeric: "798",
  },
  {
    country: "Uganda",
    alpha_2_code: "UG",
    alpha_3_code: "UGA",
    numeric: "800",
  },
  {
    country: "Ukraine",
    alpha_2_code: "UA",
    alpha_3_code: "UKR",
    numeric: "804",
  },
  {
    country: "United Arab Emirates (the)",
    alpha_2_code: "AE",
    alpha_3_code: "ARE",
    numeric: "784",
  },
  {
    country: "United Kingdom of Great Britain and Northern Ireland (the)",
    alpha_2_code: "GB",
    alpha_3_code: "GBR",
    numeric: "826",
  },
  {
    country: "United States Minor Outlying Islands (the)",
    alpha_2_code: "UM",
    alpha_3_code: "UMI",
    numeric: "581",
  },
  {
    country: "United States of America (the)",
    alpha_2_code: "US",
    alpha_3_code: "USA",
    numeric: "840",
  },
  {
    country: "Uruguay",
    alpha_2_code: "UY",
    alpha_3_code: "URY",
    numeric: "858",
  },
  {
    country: "Uzbekistan",
    alpha_2_code: "UZ",
    alpha_3_code: "UZB",
    numeric: "860",
  },
  {
    country: "Vanuatu",
    alpha_2_code: "VU",
    alpha_3_code: "VUT",
    numeric: "548",
  },
  {
    country: "Venezuela (Bolivarian Republic of)",
    alpha_2_code: "VE",
    alpha_3_code: "VEN",
    numeric: "862",
  },
  {
    country: "Viet Nam",
    alpha_2_code: "VN",
    alpha_3_code: "VNM",
    numeric: "704",
  },
  {
    country: "Virgin Islands (British)",
    alpha_2_code: "VG",
    alpha_3_code: "VGB",
    numeric: "092",
  },
  {
    country: "Virgin Islands (U.S.)",
    alpha_2_code: "VI",
    alpha_3_code: "VIR",
    numeric: "850",
  },
  {
    country: "Wallis and Futuna",
    alpha_2_code: "WF",
    alpha_3_code: "WLF",
    numeric: "876",
  },
  {
    country: "Western Sahara",
    alpha_2_code: "EH",
    alpha_3_code: "ESH",
    numeric: "732",
  },
  {
    country: "Yemen",
    alpha_2_code: "YE",
    alpha_3_code: "YEM",
    numeric: "887",
  },
  {
    country: "Zambia",
    alpha_2_code: "ZM",
    alpha_3_code: "ZMB",
    numeric: "894",
  },
  {
    country: "Zimbabwe",
    alpha_2_code: "ZW",
    alpha_3_code: "ZWE",
    numeric: "716",
  },
  {
    country: "Åland Islands",
    alpha_2_code: "AX",
    alpha_3_code: "",
    numeric: "",
  },
];
